### ISSUE TITLE
Adding an asynchronous getter (Promise) for screen availability status

### ISSUE THREAD

**Issue by mfoltzgoogle** [w3c/presentation-api#11]
From http://webscreens.github.io/presentation-api/#open-questions:

If there are already connected screens when the page subscribes to the onavailablechange event, we can handle this in two ways: We can synthesize one initial event to notify the page about available screens as soon as the first event handler is installed (as described). Or we can add another message like navigator.presentation.getAvailable(function(available) { } ); to notify the page about available screens using this one-time asynchronous getter. Which way should we go?

Also see: https://github.com/webscreens/presentation-api/issues/8

**Comment by mfoltzgoogle** [comment]
The [algorithm in current specification](http://w3c.github.io/presentation-api/#the-onavailablechange-eventhandler) is defined in terms of an event based approach, and according to the [Promises Guide](http://www.w3.org/2001/tag/doc/promises-guide#streaming-data) it's appropriate when there may be multiple results from one asynchronous getter.

We may reopen this when the [Streams API](https://streams.spec.whatwg.org/) become more fully defined.

**Comment by anssiko** [comment]
I think the current events based approach [1] is a better fit for conveying the availability information in the Presentation API, since the data involved is not large. The relevant Promises Guide section is Recurring Events [2].

An example of an API that builds upon the Streams API is e.g. TCP and UDP Socket API [3]. This API potentially produces large amounts of data and as such is a good fit for Streams API.

[1] http://w3c.github.io/presentation-api/#the-onavailablechange-eventhandler
[2] http://www.w3.org/2001/tag/doc/promises-guide#recurring-events
[3] http://www.w3.org/2012/sysapps/tcp-udp-sockets/
