### ISSUE TITLE
Convert URL passed to PresentationRequest to an absolute URL

### ISSUE THREAD

**Issue by tidoust** [w3c/presentation-api#200]
The specification remains silent on what happens to the URL passed to the `PresentationRequest` constructor. When `start` is called, the URL should be converted to an absolute one.

C.f. the "window.open" algorithm in HTML:
"resolve url relative to the API base URL specified by entry settings, and let resource be the resulting absolute URL, if any. If the resolve a URL algorithm failed, then ..."
http://www.w3.org/TR/html51/browsers.html#dom-open

Not sure what should happen if the URL cannot be resolved. Reject the promise with an `OperationError`?

Also, should this rather be done in the `PresentationRequest` constructor?

**Comment by anssiko** [comment]
It sounds like the URL should be parsed when the constructor is called. Or do we have a good reason not to? This would suggest the [Interface PresentationRequest section][1] is amended with something like:

>When the `PresentationRequest()` constructor is called, the UA must run these steps:
>* ... language to implement URL parsing ... , if this fails throw a `SyntaxError` and abort these steps. 
>* Set the presentation request URL to the result of parsing.

On the exception naming: the `WebSocket()` constructor throws a `SyntaxError` if the parsing of the URL passed as an argument to the constructor fails. Perhaps better throw a `SyntaxError` instead of an `OperationError` here as well?

[1]: https://w3c.github.io/presentation-api/#interface-presentationrequest
