### ISSUE TITLE
Specify whether properties of the Presentation are left undefined

### ISSUE THREAD

**Issue by mfoltzgoogle** [w3c/presentation-api#205]
In case a UA implements one conformance class but not the other, we may want to only expose specific properties of `Presentation`, i.e.:

* In a controlling but not receiving user agent `presentation.receiver` is not defined 
* In a receiving but not controlling user agent `presentation.defaultRequest` is not defined

The alternative is to leave them defined for all UAs but force them to be null.  In the latter case, maybe setting `presentation.defaultRequest` would throw an exception?

I am not sure about the precedent here for partial implementation of an interface object.

**Comment by louaybassbouss** [comment]
This issue is relevant for WebIDL tests which I am currently working on to prepare the test plan. Web Platform Tests Projects [1] offers a lib idlharness.js [2] for it which automatically generates browser tests for WebIDL interfaces. In our case we will have two idlharness one for each conformance class.  IDL-harness for Controlling User Agent expects that the PresentationReceiver Interface is defined even if presentation.receiver is `undefined` or `null`. 

[1]: https://github.com/w3c/web-platform-tests
[2]: http://testthewebforward.org/docs/testharness-idlharness.html

**Comment by mfoltzgoogle** [comment]
I think the spec currently addresses this, although it could be more explicit:

> In a controlling user agent, the defaultRequest attribute must return the default presentation request if any, null otherwise.

> In a receiving user agent, the receiver attribute must return the PresentationReceiver instance associated with the receiving browsing context and created by the receiving user agent when the receiving browsing context is created. In any other browsing context, it must return null.

We should update the text to state that these properties are defined for both conformance classes, and that they return null in cases where the corresponding conformance class is not implemented.

**Comment by louaybassbouss** [comment]
thx @mfoltzgoogle I will update the WebIDL-harness according to your proposal. We can also close issue #230.
