### ISSUE TITLE
Possibility for a character to be interpreted differently depending on locale

### ISSUE THREAD

**Issue by tidoust** [w3c/presentation-api#218]
Hi all,

[I'm raising this as an issue for tracking purpose, but I do not think that there is any issue in the end, so actually suggests to close it once people have reviewed it, unless someone points out that I missed something, of course!].

The group discussed potential internationalization issues during its F2F last week [1]. One particular issue that was raised was the possibility for a given character in a JS string to be interpreted differently by both browsing contexts, meaning it would be represented by different glyphs with different meaning in a Japanese, Chinese and/or Korean environment (e.g. a glyph meaning "Yen" in Japanese and a different currency in Chinese).

I said that I believed this was impossible in practice, and took an action "to investigate the possibility for a JS string to be rendered differently by different glyphs and locales".

I had a quick chat with @r12a (Richard Ishida), internationalization activity lead at W3C, and confirm that, unless I missed something in the scenario presented below, such a problem should never ever happen. The Presentation API operates on JavaScript types which are not affected by the character encoding used to retrieve the content.

The hypothetical scenario where a problem could have happened was something like:

1. the app running on the controlling browsing context is served encoded in Shift_JIS (usual encoding for Japanese characters);
2. the app running on the receiving browsing context is served encoded in Big5 (usual encoding for Chinese characters);
3. the app on the controlling browsing context extracts a string from a DOM element
4. the app on the controlling browsing context sends that string over to the receiving browsing context using the Presentation API's "send" method;
5. the app on the receiving browsing context sets the received value to a DOM element;
6. the characters rendered on the receiving browsing context for that DOM element mean something different.

In particular, regardless of the encoding used to serve a page/app, extracting a string from a DOM element returns a DOMString [2], which is an UTF-16 encoded serialization of the underlying sequence of Unicode characters (in an ideal world, this would return the sequence of Unicode character codes directly, but JavaScript strings are 16-bits only, so some characters are actually represented as two 16-bits surrogate pairs).

For instance, the Unicode character of a Japanese's "katakana letter small A" is 0x30A1, so if a DOM element contains such a letter, extracting it will yield a sequence with one integer 0x30A1, even if the document that was used to produce this element was encoded in Shift_JIS where this character is represented as a 0xA6 byte.

From the perspective of the Presentation API, the communication channel sends a DOMString to the other end point. The actual bytes sent over the channel depend on the transmission protocol: WebSocket will typically turn the DOMString into Unicode characters (thus creating what WebIDL calls a USVString) and encode the result using UTF-8 for transmission, while other protocols could do differently, e.g. Unicode character codes as 32-bit values. What is important is that the receiving end point will eventually see a DOMString, again to be interpreted as a UTF-16 encoded serialization of a sequence of Unicode characters, independently of the character encoding that was used to load the HTML content.

What may of course happen in the katakana example is that the Chinese font used on the receiving browsing context does not contain the right glyph to represent a Katakana letter small A. The character would be rendered as an unknown one in that case (perhaps as a question mark or a square). This should never produce another character with a different meaning though!

[1] http://www.w3.org/2015/10/29-webscreens-minutes.html#item07
[2] http://heycam.github.io/webidl/#idl-DOMString

**Comment by mfoltzgoogle** [comment]
Agreed that if string serialization for `send()` is capable of passing Unicode characters cleanly, then there shouldn't be an issue with the meaning of characters changing over the wire.  The spec should state that strings are passed in a way that is Unicode-clean: either USVString or the equivalent.

If the document for the receiving context is rendered using a non-Unicode encoding, and it receives a Unicode string via Presentation API, it's up to the receiving user agent to figure out a way to convert it appropriately before inserting it as text into the DOM.  Nothing new here as this problem has to also be solved for WebSockets, etc.

**Comment by tkanai** [comment]
@tidoust 
Thank you for raising the issue here, but I'm afraid that the point is slightly different. Please take a look at the gist [1]. As you can see in the picture, each Unicode code point are rendered differently depending on each language setting.  As I opened the HTML page in my Japanese PC, the cells in skyblue shows the same letters with the result of lang="ja" case, but it might be rendered differently in your environment. Please try it out. 

Most of modern browsers pick up appropriate fonts to render text depending on lang setting. To show Japanese text, or DOM nodes with lang="ja" setting, modern browsers pick appropriate/preferred Japanese font from the local system, for example.  As a result of the process, paragraphs with no lang settings, which are common, would be rendered differently in each UA with its default fall back font.
Then my concern is that the text on my browser would be rendered differently on the second screen as another language text. I don't care about any design gaps including serif /sans-serif design gaps, as long as the second screen shows the same language with the first screen.
What I would like to make sure is that the index.html in [1] would be rendered with Japanese glyph, like as the PNG image in [1] on the second screen which is owned by my friend in China/Korea/Taiwan.

[1] https://gist.github.com/tkanai/c9d64283ae14ecc5250f

**Comment by tidoust** [comment]
@tkanai 

OK, now I see what you meant, many thanks for the concrete examples! I pointed out the issue to @r12a who created an issue for the Internationalization Working Group, which should eventually get back to us:

 http://www.w3.org/International/track/issues/506

The two examples are different. My understanding is that things work "as planned" for the first set of characters, meaning that they are indeed rendered slightly differently depending on the underlying language context.

The backslash character is definitely a weird example. I suppose that there is some sort of legacy involved, as one would expect the character to be rendered as a backslash no matter what. FWIW, on my computer, MS Edge renders it properly as a backslash character in all three cases, while Chrome renders it as a backslash for the default and Japanese language and as a Won sign for the Korean language.

Anyway, these examples provide good additional rationale to recommend that the receiving browsing context uses the locale of the requesting side when possible, as discussed during the F2F.

**Comment by mfoltzgoogle** [comment]
Thank you for the example.  It is clear that simply preserving the Unicode data isn't sufficient, as locale and font selection can also change the meaning of the content.

It would be helpful for @r12a or the followup to http://www.w3.org/International/track/issues/506 point to any normative references to how locales should handled by user agents, so we can refer to them in the spec.  There is some discussion about the lang= attribute in HTML5 [1], but I feel that this is better handled at the HTTP level, e.g. by setting `Accept-Language` [2] - after all, the server may provide different content depending on the requested locale.

[1] http://www.w3.org/TR/html5/dom.html#the-lang-and-xml:lang-attributes
[2] http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.4

**Comment by tkanai** [comment]
Thank you for the comments.
@tidoust I have to admit that the backslash is an edge case. These days, web authors use U+00a5 Yen sign instead of the backslash in Japan, so I don't think it is a big issue. I guess U+20a9 Won sign is also used in Korea. The main reason why I added the issue into the example is to tell how locales/languages would affect to rendering results very clearly. For those who use CJK daily basis, the small gaps in the first example is powerful enough to stop reading. 

@mfoltzgoogle My read is that when the default lang is handled at the HTTP level, a receiver will need to keep the header information which is obtained from the sender, for further HTTP accesses. Am I correct?  I think it would be reasonable for receivers to solve the default language, or locale,  at the document level, but it is interesting.

**Comment by mfoltzgoogle** [comment]
The receiver could certainly set the lang= attribute on the presentation document to match a locale set by the sender.  However, if the server uses the `Accept-Language` value in the header as a signal for what document to serve (i.e. because strings are translated differently) then it would seem to make the problem worse.  For example, if the presentation were requested with:

```
Accept-Language: ja
``` 

and was marked up with:

```
<html lang="ko">
```

then the browser might choose a Korean font to render the Japanese content of the presentation.   I'm not an expert into how these interact, I can reach out to the Chromium community to get some clarification, or maybe @r12a can shed some light.

**Comment by aphillips** [comment]
The I18N WG is scheduled to discuss this tomorrow (12 November 2015) in our teleconference. 

I'll make a quick personal comment here, though. It is important not to confuse the presentation of a character with the interpretation or meaning of the character. The reverse solidus (backslash) character is one example. The differences between Simplified Chinese and Traditional or kanji forms is another. These are only differences in the shape of the character, however. You can still, for example, search for a \ in a document showing U+005C as a yen sign and find every occurrence.

Because the presentational variations (among other things) do matter, the ability to mark up documents and runs of text within documents with languages tags is something that the I18N WG recommends strongly. But this thread seems to be confusing the shape of the glyph with the processing that might be applied to the text.

I'm sure the working group will have additional comments. Stay tuned.

**Comment by duerst** [comment]
I concur with @aphillips, but have some additional comments.

First, it's not really about differences between Simplified and Traditional Chinese, because these are distinguished by using different code point when the difference is significant (e.g. 区 vs. 區).

The differences in Han character (kanji) shapes between mainland China, Taiwan/HK, Japan, and so on are much finer, much closer to the level of font differences. Users in each country/region are used to read these characters in their preferred shapes, but basic readability isn't affected when another shape is used. As an example, I occasionally get email that displays Japanese text with a Chinese font; although this is somewhat suboptimal, it's nevertheless readable without problems.

Depending on the person reading something, I can imagine different preferences by different people for cross-language content. I don't read Chinese, and so cannot speak from direct experience, but I could well imagine that a Japanese native person might want to see even Chinese content displayed using a Japanese font, and vice versa, because such a person is more familiar with the glyph shapes in their native fonts. The main problem would be cases where e.g. some Chinese characters are not available in the Japanese font; this might lead to a ransom note effect which of course would be undesirable.

As for the different ways of showing U+005C, this is a hopeless remainder from a time where there were a lot of local code pages. I remember a time when on a German system, the {} frequently used in C were displayed as ö or some such; the rest was done by the viewer. Unfortunately, the yen/won sign effect won't disappear soon because it would require a Y2K-like effort without a deadline.

I strongly suggest to recommend the following whenever appropriate: "To denote Japanese Yen, replace U+005C with U+00A5 (¥, Yen symbol in Latin-1), U+FFE5 (￥, full width Yen sign), 円 (Kanji for Yen),..., and to denote Korean Won, replace U+005C with U+FFE6 (￦, full width Won sign),... Only use U+005C for syntactic backslash (e.g. in programming languages). (readers of programming languages at least in Japan are used to see a Yen symbol were other readers would expect a backslash in a program)" Unfortunately, this is the best advice there's at the moment. Relying on language tagging for this issue is not appropriate and not safe enough.

**Comment by r12a** [comment]
ok, I'll try to summarise what we just discussed in the i18n telecon. 

the issue here is that some ideographic characters may look foreign to the reader unless a language-sensitive font is applied.  (btw, this can be the case for other scripts too, including arabic and latin)

we are only talking about minor differences between characters, and they are more likely to affect readability rather than meaning.  When significant differences arise, such as for 门  and 門, which have a different number of strokes, then Unicode uses separate code points, including (as for that example) to reflect the differences between Simplified and Traditional forms of the same character.   Nevertheless, it *is* a real issue, and it is important that it be addressed.  

there needs to be some information associated with the content in question that describes what language it is in.  If information is taken, say, from an HTML page, the `lang` attribute should provide that information.

in order for the appropriate font to be applied by the receiver at display time, it will be necessary to pass information with JSON strings to indicate the language of the content.  There needs to be a mechanism to allow this.  It should use BCP47 language tags.

on the receiving end, the application that handles the display of the strings needs to be able to associate a language-appropriate font with the string so that Chinese text uses Chinese font forms, and Japanese text uses Japanese font forms, etc.  All the major desktop browsers already do that (fwiw see the test results at http://www.w3.org/International/tests/repo/results/default-font – click on the text in the 'Test link' column to try the test).

HTTP's accept-language addresses a different problem (language negotiation), and so is not likely to be useful here. Basically, it is used to request a specific language variant – eg. i want the content in Chinese or in Japanese, etc.  If the content is available in that language, it can be sent to the receiver, but the problem of choosing the correct font for display still requires a knowledge of which language the content is in (which is the problem we are concerned with).

does that help?

**Comment by tidoust** [comment]
Thanks @r12a, @aphillips and @duerst , that certainly helps understanding the issue at stake.

The messages that will go through the communication channels are entirely up to the application. We may add a note to recommend that authors flag strings with a BCP47 language code but won't be able to do more than that.

The main reason why the Second Screen WG is considering the ability to pass the language(s) to the receiver for use in the `accept-language` negotiation phase is not to solve the particular issue mentioned here, but indeed to allow the controller to specify the language it would want the content on the receiving side to appear in (e.g. to force the display of a page in French if the controller side is also in French.

My understanding is that, is such a mechanism is in place, it would also address the language-specific font selection issue that is at stake here: if the controlling side can tell the receiving side to override its language settings to Japanese before it downloads the content, the receiving side could also use that info to use a Japanese font as default font in the absence of other information.

**Comment by r12a** [comment]
> My understanding is that, is such a mechanism is in place, it would also address the language-specific font selection issue that is at stake here: if the controlling side can tell the receiving side to override its language settings to Japanese before it downloads the content, the receiving side could also use that info to use a Japanese font as default font in the absence of other information.

i'm not sure that really follows. Suppose the language asked for is not available.  Usually the server would fall back to another language...

Also, the accept-language data is set in the browser and is unlikely to be altered much of the time. In fact, in some browsers it's not possible to easily change it.  If you speak both Chinese and Japanese, say, and wanted to receive information in both languages from one time to the next, it would be a pain, if possible at all, to change the accept-language header depending on which language you wanted to read.  And if your accept-language setting was set to en but you still wanted to see the content properly rendered (as might be the case for someone like myself), you'd be back to the situation of pot-luck as to whether ideographic characters were married to the right font.  This would also be the case for a Japanese/Chinese person looking up data in one of those languages in an internet cafe in the UK.

Thirdly, what about a situation where some of the data is in Japanese, and some in Chinese. Accept-language is too blunt an instrument to handle that at all.

Trying to use accept-language in this way seems to me rather like the proverb that if you only have a hammer everything looks like a nail.  Accept-language is only meant to indicate language preferences, not interpret what to do with content.  I think that the data itself needs to identify the language of its content.

**Comment by tidoust** [comment]
>> My understanding is that, is such a mechanism is in place, it would also address the language-specific font selection issue that is at stake here: if the controlling side can tell the receiving side to override its language settings to Japanese before it downloads the content, the receiving side could also use that info to use a Japanese font as default font in the absence of other information.

> i'm not sure that really follows. Suppose the language asked for is not available.  Usually the server would fall back to another language...

Right, but I don't think that matters for our use case. See the Internet café example below.

> Also, the accept-language data is set in the browser and is unlikely to be altered much of the time. In fact, in some browsers it's not possible to easily change it.

What is specific to the Presentation API is the existence of a control channel that the controlling user agent uses to send commands such as "load that URL" to the receiving user agent. How this works in practice is up to implementations for the time being, but it is easy to envision that this control channel could also be used to pass language settings to the receiving user agent so that it temporarily alters its language settings.


>  If you speak both Chinese and Japanese, say, and wanted to receive information in both languages from one time to the next, it would be a pain, if possible at all, to change the accept-language header depending on which language you wanted to read.  And if your accept-language setting was set to en but you still wanted to see the content properly rendered (as might be the case for someone like myself), you'd be back to the situation of pot-luck as to whether ideographic characters were married to the right font. This would also be the case for a Japanese/Chinese person looking up data in one of those languages in an internet cafe in the UK.

Who is "you" in this description? With the Presentation API, we have two potential "you": one "you" is the controlling user agent, and the other "you" is the receiving user agent. In most envisioned scenarios, the user would be the same, so we would prefer both underlying user agents to behave similarly.

If a Japanese person goes to an Internet café in the UK with her Japanese smartphone (the controlling user agent) and wants to make use of a second screen available there to render a given URL, she would probably want the second screen (the receiving user agent) to render the content at that URL as it would be rendered on her smartphone.

If the content is served in Japanese through HTTP content negotiation on her smartphone, then she would want to see the Japanese version on the second screen as well, if possible. And so, she would want her controlling user agent to tell the receiving user agent to temporarily switch to the same language settings as her smartphone before it downloads and renders the page.

If the content is served in English even when Japanese is requested, then so be it, she would see the content in English on the second screen as she would see the content in English on her smartphone, perhaps still using a Japanese variant of an English font (if such a thing exists) in both cases.

What we would prefer to avoid is a situation where she sees English on the second screen while she would see Japanese on her smartphone. Said differently, the second screen is to be an extension of her smartphone, not a completely separated device.


> Thirdly, what about a situation where some of the data is in Japanese, and some in Chinese. Accept-language is too blunt an instrument to handle that at all.

That's understood, I am not suggesting we can solve this particular point with an `accept-language` hammer. I hope the above example explains the background better.

**Comment by r12a** [comment]
oh, this is a very different use case than the one i thought we were talking about. In this case, it seems to make sense to pass the smartphone's accept-language settings to the second screen and require the browser to pass that to the server from which it is requesting the resource.

i thought we were talking about passing strings from the smartphone to the second screen, or vice versa, for display, and that's the case where i see the necessity of passing the language of the string with the string.

**Comment by tomoyukilabs** [comment]
> In this case, it seems to make sense to pass the smartphone's accept-language settings to the second screen and require the browser to pass that to the server from which it is requesting the resource.

I think it make sense, too. If I understand it correctly, this mechanism seems to need to be implemented in the control protocol, since the receiving user agent needs to know the controlling user agent's accept-language setting before loading a receiver Web app. Now I am wondering whether existing control protocols for the 2-UA case might have such a mechanism or not...

**Comment by mfoltzgoogle** [comment]
Reviewing this thread in light of our desire to publish a Candidate Recommendation for the Presentation API.

Some background: I reached out a while ago to blink-dev@ and got feedback that indeed, the lang= does influence font selection when rendering. [1]

It sounds like there are two distinct issues that we may want to address with specification language.

1.  When a user requests presentation, the receiving browsing context SHOULD apply the language settings of the controlling browsing context, so that when the receiving user agent fetches resources for the presentation an appropriate HTTP `accept-language` header is set.  (This is not a requirement, as the controller could also append a locale (BCP47) tag to the presentation URL passed to the server for language-specific resources.)

2. When a human-presentable string is passed from the controller to the receiver (or vice versa), the application MAY want to include a locale tag describing the preferred display language for the string to assist the browser with font selection.   The page would be responsible for taking this locale and setting the lang= tag on the appropriate element rendering the string.

In the scope of the current Presentation API, I believe item 1 would be included as guidance for implementors and 2 as guidance for authors.  I can craft a PR along these lines.

Both 1 and 2 would certainly be features that we could include in a forthcoming presentation control protocol.

[1] https://groups.google.com/a/chromium.org/d/msg/blink-dev/7O6NPCuVWlo/1CwqmrQ4AQAJ

**Comment by mfoltzgoogle** [comment]
Also: I can also include a note to avoid ambiguous characters like backslash, but that seems like general Web development guidance and not specific to Presentation API.

**Comment by tomoyukilabs** [comment]
@mfoltzgoogle Thank you. Both item 1 and 2 look good to me. As you mentioned, authors can solve item 2 by themselves, while item 1 needs implementation of `accept-language` support. Thus I also think item 1 as guidance for implementors and item 2 as guidance for authors make sense.

> Also: I can also include a note to avoid ambiguous characters like backslash, but that seems like general Web development guidance and not specific to Presentation API.

I agree with this.

**Comment by mfoltzgoogle** [comment]
PR #280 contains my suggested language along the lines above.  PTAL

**Comment by mfoltzgoogle** [comment]
Closing with the merge of PR #280.
