### ISSUE TITLE
Have the receiving browsing context generate the presentation identifier?

### ISSUE THREAD

**Issue by tidoust** [w3c/presentation-api#253]
In the spec, the presentation identifier identifies a receiving browsing context. To reconnect to a session running on some receiving user agent, all a Web app should need is the presentation identifier and the presentation URL. This allows to pass the identifier from one user agent to the other.

For this to work, the receiving user agent needs to know how to associate a presentation identifier with a receiving browsing context. I assume this means that the presentation identifier must be exchanged somehow between the controlling user agent and the receiving user agent.

However, right now, the presentation identifier is generated by the controlling user agent, which seems odd: no matter how unlikely, two controlling user agents could perhaps generate the same identifier for two contexts running on a receiving user agent, leading to possible confusions.

Wouldn't it make more sense for the receiving user agent to generate the identifier itself and pass it to the controlling user agent when the connection is established?

Or is the presentation identifier meant to be only known by the controlling user agent and not passed around to the receiving user agent at all?

**Comment by mfoltzgoogle** [comment]
> Or is the presentation identifier meant to be only known by the controlling user agent and not passed around to the receiving user agent at all?

The current spec does pass the identifier from the controller to the receiver [1].  Since additional controllers need the same identifier to reconnect it seems like the same identifier will get used for all connections? 

There is an issue you note with different receiving contexts within the same receiving user agent ending up with the same presentation URL and identifier.  In fact, it looks like the method of generating the identifier was dropped from the "starting a presentation" algorithm.  If we defined it to almost-guarantee uniqueness of the identifier, it would seem to address the issue.

One problem with having the receiver generate the identifier:  we won't be able to resolve a new PresentationConnection on the controller in a "connecting" state, since we don't yet have the identifier from the receiver.

[1] https://w3c.github.io/presentation-api/#monitoring-incoming-presentation-connections

**Comment by tidoust** [comment]
> One problem with having the receiver generate the identifier: we won't be able to resolve a new PresentationConnection on the controller in a "connecting" state, since we don't yet have the identifier from the receiver.

Yes, or the `id` attribute would need to return `null` as long as the identifier is not known, but that looks bad.

Anyway, my initial worry misses one counter-example: if the identifier is generated by the receiving user agent, two receiving user agents could also still create the same identifier for a given presentation connected to two different tabs of a controlling user agent. In such a case, a page running on the controlling user agent would not be able to select the right presentation connection when calling `reconnect`.

I suggest to close this issue: no matter where the identifier gets generated, the main issue is indeed that we probably want to reduce the likelihood that the identifier may clash with another one created in its vicinity. And it does make things more complicated from a spec perspective since the spec expects the identifier to be available right away on the controlling side.

I created issue #279 (Specify the algorithm for generating a presentation identifier) to discuss the generation of the presentation identifier.

**Comment by mfoltzgoogle** [comment]
PR #284 specifies the algorithm for setting the id and also passes the id from the controller to the receiver, so that the id should be the same for all connections to the presentation.

**Comment by mfoltzgoogle** [comment]
Closing with the PR to clarify about ID passing.
