### ISSUE TITLE
travis-cl complains about obsolete nvm version

### ISSUE THREAD

**Issue by mfoltzgoogle** [w3c/presentation-api#265]
When publishing the last working draft, travis-cl complained that the version of `nvm` is out of date:

```
0.94s$ nvm install 0.10
######################################################################## 100.0%
Now using node v0.10.42
npm WARN deprecated This version of npm lacks support for important features,
npm WARN deprecated such as scoped packages, offered by the primary npm
npm WARN deprecated registry. Consider upgrading to at least npm@2, if not the
npm WARN deprecated latest stable version. To upgrade to npm@2, run:
npm WARN deprecated 
npm WARN deprecated   npm -g install npm@latest-2
npm WARN deprecated 
npm WARN deprecated To upgrade to the latest stable version, run:
npm WARN deprecated 
npm WARN deprecated   npm -g install npm@latest
npm WARN deprecated 
npm WARN deprecated (Depending on how Node.js was installed on your system, you
npm WARN deprecated may need to prefix the preceding commands with `sudo`, or if
npm WARN [35mdeprecated on Windows, run them from an Administrator prompt.)
npm WARN deprecated 
npm WARN deprecated If you're running the version of npm bundled with
npm WARN deprecated Node.js 0.10 LTS, be aware that the next version of 0.10 LTS
npm WARN deprecated will be bundled with a version of npm@2, which has some small
npm WARN deprecated backwards-incompatible changes made to `npm run-script` and
npm WARN deprecated semver behavior.
```

I am not sure how to update the version of `nvm` run in the container but can investigate.

On the other hand, the only thing our travis-cl script does is to run `curl`; I am wondering if we need to mess with node.js at all.

**Comment by tidoust** [comment]
See proposed pull request. We do not need Node.js at all and do not impose any version of nvm, so the error was on Travis CI side. That seems to have been fixed since no warnings were logged last time we published the spec.

Travis CI used to force people to select a specific language environment, but introduced a "generic" language some time ago as a way to say "no particular language, I'm just going to use bash commands":
https://github.com/travis-ci/travis-ci/issues/2856
("bash" being a synonymous of "generic")

(FWIW, that "generic" value does not seem to appear in the documentation)

I successfully tested the value with a dummy repo.
