### ISSUE TITLE
define error handling if fail to establish presentation connection on receiving UA

### ISSUE THREAD

**Issue by schien** [w3c/presentation-api#283]
In [section 6.7.1](https://w3c.github.io/presentation-api/#monitoring-incoming-presentation-connections) we always add a PresentationConnection with 'connected' state in to connection list. However it doesn't specify the error handling if UA fails to establish connection.

My suggestion is adding a PresentationConnection with 'closed' state but not fire `connectionavailable` event. Controlling page can leverage connection resumption to reconnect to presented content.

**Comment by avayvod** [comment]
What about using the "connecting" state to match the controlling context?

**Comment by schien** [comment]
`connecting` state looks like a temporary state that will be switching to other state soon without intervene. Personally I prefer a stable state like `closed` so that I know I need to explicitly trigger some action to enter `connected` state.

**Comment by avayvod** [comment]
But as I understand, one would not need to trigger any action to enter 'connected' state, it's up to the UA. What action did you have in mind?

Currently, the receiving context will create a 'connected' PresentationConnection object and fire 'connectionavailable' with it. If there's an error establishing connection, either the event is not fired at all (if reading the algorithm steps, establishing the actual connection is a step before queuing the event) or the connection changes the state to 'closed' (if reading the afterwords saying that the event should be fired as soon as the PresentationConnection object is created).

With the 'connecting' state as the initial one, the PresentationConnection is created and the event is fired as soon as the UA gets the connection request. Then it either changes its state to 'connected' if everything went ok or 'closed' if something failed.

On the other hand, is there a good use case why the presentation page should get notified about this? I'd say the UA handles the connection request and only creates the PresentationConnection with 'connected' state and fires the event if the connection is successful. Otherwise, the page shouldn't even know there was a request to connect - it's left up to the UA to handle.

**Comment by schien** [comment]
> But as I understand, one would not need to trigger any action to enter 'connected' state, it's up to the UA. What action did you have in mind?

Here is the behavior I have in mind after reading the draft updated yesterday.

If UA is still retrying the connection establishment, staying in `connecting` state on both controller and receiver is reasonable. If UA stops retrying connection establishment, this PresentationConnection should enter 'closed' state on both controller and receiver.

On controller side, a statechange (from `connecting` to `closed`) event should be fired afterward so that controlling page can trigger connection resumption either automatically or by user action.

On receiver side, presentation controllers promise should not be resolved and this PresentationConnection should not be added into PresentationConnectionList. Presented Content will have no knowledge about this closed connection because web page cannot get the reference via any API or event, so it'll looks like that UA is still awaiting the incoming connection.

Maybe we can add more detail in step 5, like:
```
If connection completes successfully, Set the presentation connection state of S to connected.
Otherwise, set the presentation connection state of S to closed and abort all remaining steps. 
```

**Comment by avayvod** [comment]
That phrasing sounds good to me.

We may have a use case for the receiver to know about the connecting happening. For example, a game could indicate that the second player is trying to connect on the second screen for the first player to be aware and show success / failure depending on whether the state changes to 'connected' or 'closed'. However, this behavior can be added later if the use case is real.

**Comment by schien** [comment]
Agree. With current API game developer can already show 'waiting for player' / 'here comes a challenger' via `connectionavailable` event. Revealing the PresentationConnection in `connecting` state doesn't add much value IMO.

**Comment by mfoltzgoogle** [comment]
Sounds reasonable.  The editor welcomes pull requests that implement your suggestions :)

**Comment by mfoltzgoogle** [comment]
Addressed by the PR by @schien implementing the suggestion in https://github.com/w3c/presentation-api/issues/283#issuecomment-213311818.  Thanks!
