### ISSUE TITLE
Consider use cases for Presentation API v2 with VR capable displays

### ISSUE THREAD

**Issue by mfoltzgoogle** [w3c/presentation-api#444]
The following use cases should be considered as possibilities for better support of presentation of (and presentation from) VR content.

* Attaching a wired VR headset to a controlling user agent (e.g., PC) and launching a presentation of WebVR content to the headset from that PC.
* Initiation of presentation on another display/device while viewing WebVR content with a headset.  The other display could support VR content or be a traditional flat screen.
* Automatically starting presentation when an external VR headset is attached to PC.

The user interface impacts (security enamel, etc.)  should be thought through in immersive environment as well as the behavior of the presentation (receiving browsing context).

Also this may be a use case for capability detection: if the presented page only makes sense in VR mode, only VR-capable displays should be shown as compatible.

CC @toji @cvan from the WebVR community group as a heads up/potential for future liason.

**Comment by louaybassbouss** [comment]
+1  I am watching also the activities of WebVR and will be happy to help on this if needed

**Comment by anssiko** [comment]
@mfoltzgoogle, thanks for the proposal. This is timely input for the v2 discussions at the [Second Screen WG F2F][1] at TPAC.

I just sent a [call for v2 feature proposals][2] mail to the group to solicit further input.

[1]: https://www.w3.org/wiki/Second_Screen/Meetings/Nov_2017_F2F#Agenda
[2]: https://lists.w3.org/Archives/Public/public-secondscreen/2017Oct/0059.html

**Comment by toji** [comment]
We talked about this in the WebVR group's call today. Wanted to communicate a couple of key points that came up:

Early in the lifetime of the WebVR API using the Presentation API as the primary mechanism for presenting content to a headset was discussed but ultimately dropped. The biggest motivator for that was that we had seen that it was highly desirable for developers to load and display their 3D content while browsing normally and then transition to showing the same content in VR without incurring a reload. It appeared that using the Presentation API would effectively force content to be reloaded on the headset every time, given that the content to be shown is communicated via URL.

At the same time we have many VR devices that use the same physical display for both 2D browsing and VR content. (This mostly refers to [mobile devices paired with a viewing harness](https://vr.google.com/daydream/smartphonevr/) today, but will soon be true for a variety of [standalone devices](https://www.oculus.com/go/) as well.) The Presentation API felt poorly suited for managing mode switches of a single device rather than issuing navigation commands to an external one.

For both of those reasons we feel the Presentation API is not appropriate for launching VR content on most headsets. The other use case called out in the original post seem appealing, however! It's not entirely clear to the WebVR group what would need to be done to support them.

Certainly using the Presentation API from within VR to begin displaying content on an external screen would be nice. It seems to me, though, that such use should generally work with the API as specced today without change? (Browsers may have to ensure that appropriate native UI can be shown in a VR context, of course.) It should be noted that this would probably NOT be used for mirroring VR content to an external screen, as most existing devices have native, optimized mechanics to do so. Controlling, say, presentation of a slide deck externally from within VR would be sensible though. (Public speaking simulator?)

The flip side to that is probably the most appealing scenario: Assume that you have a desktop or laptop and, independently, a standalone VR headset (not connected to the PC.) If a user encounters interesting looking VR content while using the PC they could presumably use the Presentation API to  open the page they are looking at on the VR device rather than being forced to put on the headset and re-navigate to the same location with an in-VR browser. (Assuming I understand the spec correctly.) Additionally, it could be beneficial to instruct the page being opened that way that you'd like it to immediately start displaying the VR content rather than opening first to the 2D version of the page. This normally requires a user gesture, but the Presentation API could provide the appropriate permissions to bypass that requirement.

(Note that this would require the VR scenes resources to be re-loaded on the VR device as outlined previously, but in this scenario that couldn't be avoided no matter what the user did.)

So that's our initial thoughts on ways the two APIs could interoperate. It would be helpful to get feedback on if any of the above represents a fundamental misunderstanding of some aspect of the Presentation API.

--Brandon

**Comment by louaybassbouss** [comment]
Thx @toji  feedback from my side: 

> For both of those reasons we feel the Presentation API is not appropriate for launching VR content on most headsets. The other use case called out in the original post seem appealing, however! It's not entirely clear to the WebVR group what would need to be done to support them.

This is correct but there are two implementation modes 1-UA and 2-UA. in 1-UA mode both pages (sender and receiver pages) are rendered on the controller device but the video output of the receiver page will be captured and displayed on the receiver display. In case of VR the 1-UA mode could implemented in a way that both sender and receiver pages are displayed on the same HMD. But the receiver page will still be loaded via URL and there are two page contexts as you mentioned.  IMO I see more potential for collaboration between WebVR API and RemotePlayback API for 360° videos but this requires native 360° video playback in the browser. 

> Certainly using the Presentation API from within VR to begin displaying content on an external screen would be nice. It seems to me, though, that such use should generally work with the API as specced today without change?

I agree with you this can be done without any changes. The only thing needed is the capability detection which is not currently supported in the API, but there an issue #348 for this. In VR case you don’t need to offer all TVs in your network if your application is looking only for VR displays. 

>  This normally requires a user gesture, but the Presentation API could provide the appropriate permissions to bypass that requirement.

The Presentation API requires user gesture only to start a presentation in this case on the HMD. The Presentation API doesn’t say anything about available APIs and their restrictions on the receiver UA. But in most Presentation API use cases, it doesn’t make sense to require use gesture on the receiver page otherwise this will break the use experience (imagine a user starts a receiver page that plays a video on TV via Presentation API and he still need to press the play on the Remote control in order to play the video).

**Comment by toji** [comment]
Thanks for the reply. Sounds like modulo a few implementation details we're on the same page.

> The Presentation API requires user gesture only to start a presentation in this case on the HMD. The Presentation API doesn’t say anything about available APIs and their restrictions on the receiver UA. But in most Presentation API use cases, it doesn’t make sense to require use gesture on the receiver page otherwise this will break the use experience (imagine a user starts a receiver page that plays a video on TV via Presentation API and he still need to press the play on the Remote control in order to play the video).

This is actually what I meant, though I didn't state it well. The user gesture on the sender would be sufficient to allow the user gesture requirement to be bypassed on the receiver, going straight into the VR content with no further user interaction needed.

**Comment by mfoltzgoogle** [comment]
From https://www.w3.org/2017/11/06-webscreens-minutes.html#x18:

ACTION: @anssiko to report back our findings to the WebVR CG
ACTION: @schien  to talk to Mozilla's WebVR people in Taiwan and seek their feedback

**Comment by anssiko** [comment]
> ACTION: @anssiko to report back our findings to the WebVR CG

Downstream issue: https://github.com/w3c/webvr/issues/304

**Comment by schien** [comment]
Talked to Mozilla WebVR people today, basically they have the same feedback as @toji states in previous comments. The main difference between the Presentation API use case and WebVR use case is that WebVR is still single screen application and the user control is switched to the head gear while using it. Therefore, the extra benefit of allowing browser content to communicate with the screen on VR device is not useful for their application.

**Comment by anssiko** [comment]
WebVR CG (or Immersive Web CG nowadays) agreed to the following proposed resolution in https://github.com/immersive-web/webxr/issues/304

>Proposed resolution: no Presentation API spec changes needed, required changes are implementation details. Capability detection for VR displays (for Presentation API) is a nice-to-have feature, currently not prioritized (tracked in #348).

Mozilla’s feedback and position is similar.

Closing the issue. If new information emerges we can revisit at a later date.
