### ISSUE TITLE
Multiple presentation URLs including non-http/https URL

### ISSUE THREAD

**Issue by tomoyukilabs** [w3c/presentation-api#446]
I am wondering how non-http/https URL like `dial:` should be handled in [Constructing a presentation request](http://w3c.github.io/presentation-api/#constructing-a-presentationrequest).

I've found an issue: The recent update on WPT has replaced a URL including Cast ID into `dial:`. (see https://github.com/w3c/web-platform-tests/pull/7410). This change works well on Chrome, however calling Presentation API on Firefox for Android would result in `SecurityError` due to the `dial:` URL

This behavior seems to be based on the current spec:

> If any member of presentationUrls is not an a priori authenticated URL, then throw a SecurityError and abort these steps. 

I guess that we should additionally consider how to deal with multiple URLs including incompatible one. WDYT?

**Comment by tidoust** [comment]
That's a good point. The specification is clear that behavior for schemes over than `http` and `https` is not defined, but in that case, we probably want to clarify that implementations must ignore the URLs that they do not understand, so that an `https` URL can be used as a fallback to a URL that the user-agent does not understand.

One way to solve this would be to complete current step 5.1 to say something like:

"and add the resulting absolute URL (if any, **and if the resulting scheme is supported**) to `presentationUrls`"

... and introduce a new step 6. that says:

"If `presentationUrls` is an empty list, then throw a `NotSupportedError` and abort all remaining steps"

**Comment by tomoyukilabs** [comment]
> we probably want to clarify that implementations must ignore the URLs that they do not understand

I agree with that. The current spec is to check potential security of the URL, and now we want to check URL scheme compatibility here as well.

> "and add the resulting absolute URL (if any, and if the resulting scheme is supported) to presentationUrls"

LGTM.

**Comment by anssiko** [comment]
Marked as v1.

**Comment by mfoltzgoogle** [comment]
LGTM.  Feel free to craft a PR with this suggested change.  However we should certainly check back with Mozilla to see if they agree with the language.

**Comment by tomoyukilabs** [comment]
I've submitted the corresponding PR, however I'll update it when any additional change is suggested. Thanks for your review, @mfoltzgoogle.

**Comment by tidoust** [comment]
I reviewed the [updated tests](https://github.com/w3c/web-platform-tests/pull/9966) @tomoyukilabs prepared but now realize that I pressed the "merge" button for the tests a bit too early, given that the PR against the Presentation API is still pending. Sorry about that!

I did not revert the changes made to the tests because they seem good regardless of the prose that might end up in the spec.

**Comment by tomoyukilabs** [comment]
Of course I can update the corresponding tests again when any additional change happens here. Anyway, thanks for your review, @tidoust!

**Comment by mfoltzgoogle** [comment]
I believe this can be closed out with PR #447.
