### ISSUE TITLE
BinaryType enum is already defined in HTML

### ISSUE THREAD

**Issue by foolip** [w3c/presentation-api#456]
https://w3c.github.io/presentation-api/#interface-presentationconnection defines `enum BinaryType { "blob", "arraybuffer" };
`

However, https://html.spec.whatwg.org/multipage/web-sockets.html#the-websocket-interface includes the same, happily with the same values.

Grepping in https://github.com/tidoust/reffy-reports/tree/master/whatwg/idl, I believe this is the only enum defined twice across web specs.

The fix would be to simply remove the definition and it will probably auto-link to https://html.spec.whatwg.org/multipage/web-sockets.html#binarytype.

**Comment by tidoust** [comment]
Right. This is very likely going to change soon as W3C/WHATWG come to a mutual agreement on HTML but, up until now, the Director has asked that W3C specs that reach Proposed Recommendation and Recommendation reference the W3C version of HTML. This is what the Presentation API does in anticipation of the transition.

The `BinaryType` enum is not defined in HTML 5.x. and, while it should be defined there, it is not defined in the W3C version of the Web Sockets API (which is a section in WHATWG HTML) because the Web Platform Working Group has not maintained that draft in the past few years. At the same time, that group has not officially abandoned the Web Sockets API spec either.

In other words, `BinaryType` is not defined anywhere from a strict W3C perspective, and so the Presentation API defines it. We may drop the definition of `BinaryType` from the Presentation API right away in anticipation of an update of the W3C version of the Web Sockets API or in anticipation of a change in normative references rules. Or keep it until the situation changes. It's probably better to drop the definition now because the Presentation API shouldn't be the spec defining that enum. I suggest we keep the issue open in any case.

> Grepping in https://github.com/tidoust/reffy-reports/tree/master/whatwg/idl, I believe this is the only enum defined twice across web specs.

That's the only enum, but note there are [other redefined IDL terms](https://tidoust.github.io/reffy-reports/whatwg/perissue.html#list-of-webidl-names-defined-in-more-than-one-spec) (`BinaryType` is missing from that list for now because last crawl failed to parse the HTML spec, and as far as I can tell, the occurrence of `Worklet` is a bug that I need to investigate)

**Comment by foolip** [comment]
Alright, since I just stumbled on it and it's not causing any real trouble, I'm OK with leaving this open. Note that I already sent https://github.com/w3c/presentation-api/pull/457, which I'll also leave open. (Will probably begin to conflict eventually.)

**Comment by mfoltzgoogle** [comment]
I went ahead and merged the PR, before reading the comment by @tidoust. It sounds like we are okay dropping BinaryType from the spec in anticipation of definition in another spec (either WHATWG WebSockets, or an updated W3C WebSockets spec).  Let me know if you'd rather revert the PR to keep the status quo.

At any rate, leaving this issue open for now.

**Comment by foolip** [comment]
Oops. I should have commented on the PR as well, and won't mind if it's reverted.
