### ISSUE TITLE
Presentation API cast app ID's broken on chromium 95

### ISSUE THREAD

**Issue by ThaUnknown** [w3c/presentation-api#500]
Steps to reproduce the problem:
1. Go to https://googlechrome.github.io/samples/presentation-api/cast.html
2. Try starting a presentation request.
3. Browser Fails to connect to presentation receiver.

What is the expected behavior?
[Works correctly on chromium 90]
1. Go to https://googlechrome.github.io/samples/presentation-api/cast.html
2. Try starting a presentation request.
3. Browser connects to presentation receiver, closes connection after a few seconds of inactivity as expected.

What went wrong?
When using cast app ID's after ~30 seconds of failing to connect to the presentation receiver, you receive a 'Launch error', the presentation is started, but the connection is never established.

Did this work before? Yes Chromium 90 or later

Does this work in other browsers? Yes

Chrome version: 95.0.4638.69  Channel: stable
OS Version: 10.0

This only fails with cast app ID's, giving a direct file URL works, but only on PC, on android/linux direct file URL's don't work [fails to find presentation displays].

I filed the issue here: https://bugs.chromium.org/p/chromium/issues/detail?id=1267048

**Comment by anssiko** [comment]
@ThaUnknown thank you for reporting this issue in the Chromium bug tracker too. That is the appropriate place for implementation issues and bugs. This repo is for specification development related discussions.

@mfoltzgoogle please check whether this report motivates changes to the specification. Otherwise, this issue can be closed and resolution tracked in the Chromium bug tracker.

**Comment by mfoltzgoogle** [comment]
@ThaUnknown We will post updates on the Chromium issue  you filed. Thanks
