### ISSUE TITLE
Cannot present on multiple devices from the same tab

### ISSUE THREAD

**Issue by raghupviyer** [w3c/presentation-api#516]
According to the Docs,
[https://www.w3.org/TR/presentation-api/#creating-a-second-presentation-from-the-same-controlling-page](https://www.w3.org/TR/presentation-api/#creating-a-second-presentation-from-the-same-controlling-page)
We can control multiple displays from the same page,
but it does not work. when we perform presentation.start() the second time, a popup comes which only gives an option to stop the currently presenting display, not to present to another display
I have to open the webpage on another tab and keep doing the same thing for this

**Comment by mfoltzgoogle** [comment]
@raghupviyer What browser were you testing this on?

Chrome has a limitation that only one tab may be mirrored at a time, but the situation you describe sounds different.

**Comment by raghupviyer** [comment]
hi @mfoltzgoogle I was testing this on Chrome, I wanted to control multiple displays from the same tab  and be able to communicate different messages to the different displays at the same or different time, which according to the docs it should be possible but it seems it only supports one display per tab

**Comment by mfoltzgoogle** [comment]
Hi @raghupviyer thank you for bringing this to my attention.  After some internal discussions, this situation is a side effect of a recent change to the Chrome UI to merge presentation functionality with media controls.  As it currently stands there is no way to start a second presentation from the same tab.

I filed https://crbug.com/1496105 in the Chrome bug tracker so you can track our progress in bringing back this capability.   We continue to evolve our UI so hopefully it won't be too long.   In the meantime, I may also change the implementation to throw a different exception (`NotFoundError`) to better match the semantics of the spec.

Since this is a Chrome issue and not an issue with the spec, I'm closing this out.

**Comment by raghupviyer** [comment]
Thankyou @mfoltzgoogle , appreciate it a lot
