### ISSUE TITLE
Define exceptions to be thrown in startSession and joinSession rejection

### ISSUE THREAD

**Issue by mfoltzgoogle** [w3c/presentation-api#78]
The [algorithms for startSession and joinSession](http://w3c.github.io/presentation-api/#starting-a-presentation-session) indicate that specific error types like `PermissionDenied` and `NoPresentationFound` should be used when rejecting the Promises returned to the caller.  However @avayvod has pointed out these types are not part of the [`DOMException` list for WebIDL](http://heycam.github.io/webidl/#dfn-DOMException).

If we wish to use these types we should define our own `PresentationError` object with Presentation-API specific error types.

Alternatively, we could try to re-use existing `DOMException` types, which seems to be done in other specs (Push API, Service Workers API).

Also see:
* [MediaStreamError](http://www.w3.org/TR/mediacapture-streams/#mediastreamerror)

**Comment by anssiko** [comment]
I believe we should reuse the `DOMException` types, if the API just needs a way to represents an error, with no additional data (such as in the `MediaStreamError`'s case, `constraintName`) beyond the optional `message` that can be used to convey user agent-defined human readable details of the error for debugging purposes.

For example, we could simply throw `NotSupportedError` in both the cases.

I'll tag this for F2F discussion, since this should be a relatively quick one.

**Comment by mfoltzgoogle** [comment]
I would also be in favor of re-using `DOMException` in the spec and using the human-readable message to provide the exact issue to the developer.

Unless there are arguments otherwise, we'll close this issue when the spec has been updated to throw `DOMException` types for error cases.

**Comment by anssiko** [comment]
@mfoltzgoogle Sounds good. I'd consider this a minor change that aligns the spec with the platform conventions.

Please feel free to submit a PR with "Fixes #78" in the commit message and merge it. That should automatically close the issue (thanks to https://help.github.com/articles/closing-issues-via-commit-messages/).

If any of the group participants have concerns with the change, we can always reopen the issue.
